
CREATE TABLE stu (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  age INT NOT NULL,
  status TINYINT(1) NOT NULL DEFAULT 0
);


-- ALTER TABLE stu ADD COLUMN status TINYINT(1) NOT NULL DEFAULT 0;
